---
#-------------------------------
# General Site Settings

title: Fu Lab
logo: 
author: yusifu
description: this is meta description
email: yusifu@creighton.com
phone: +880 2544 658 256
address: 125/A, CA Commercial Area, California, USA
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: Research, link: "/research" }
  - { name: Lab Members, link: "/labmembers" }
  - { name: Publications, link: "/publications" }
  - { name: Join the Lab, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Single-Cell Genomics <br> in <br> Aging & Cancer

social:
 # - { icon: "ti-facebook", link: "#" }
 # - { icon: "ti-instagram", link: "#" }
 # - { icon: "ti-dribbble", link: "#" }
 # - { icon: "ti-twitter-alt", link: "#" }

  #- { icon: "ti-google", link: "https://scholar.google.com/citations?user=A8SgYIcAAAAJ" }
  #- { icon: "ti-email", link: "mailto:YusiFu@creighton.edu" }

#-------------------------------
# About (Section and Page)



# Work Process/field Section
work-process:
  - title: "Cancer Genomics"
    icon: "assets/images/icons/logo1.svg"
    content: "Cancer embodies a heterogeneous progression with diverse genetic underpinnings. Our research dives deep into its genomic landscape to decipher patterns and potential therapeutic targets."
  
  - title: "Aging and Longveity"
    icon: "assets/images/icons/logo2.svg"
    content: "Aging is a multifaceted biological journey shaped by genetics and environmental factors. Our work seeks to understand its molecular drivers and potential avenues to promote longevity."

  - title: "Hearing Loss"
    icon: "assets/images/icons/logo3.svg"
    content: "Hearing impairment can be influenced by various genetic and environmental factors. Our research aims to elucidate the genetic predispositions and underlying mechanisms contributing to hearing loss."


# My Team Section

team:
  - title: "Na Zhong"
    image: "assets/images/team/NaZhong1.png"
    designation: "Lab manager"
  
  - title: "Shiwei Yin"
    image: "assets/images/team/ShiweiYin1.png"
    designation: "Laboratory Operations Manager"
  
  - title: "Yingzi Liu"
    image: "assets/images/team/YingziLiu1.png"
    designation: "Lab technician"
  
  - title: "Sneha Pradhan"
    image: "assets/images/team/SnehaPradhan1.png"
    designation: "Master Student"

  - title: "Ariana Kaneda"
    image: "assets/images/team/ArianaKaneda1.png"
    designation: "Undergraduate Student"

#-------------------------------
# Publication (Section and Page)


# Portfolio Page
portfolio-label:
 # - { title: "Cancer Genomics", type: "cancer" }
  - { title: "Metholdology", type: "sc" }
  - { title: "Aging", type: "aging" }
 # - { title: "Hearing Loss", type: "hearing" }

portfolio-items:
  - image: "assets/images/portfolio/7.agingatlas.png"
    url: "https://www.biorxiv.org/content/10.1101/2023.02.28.530490v4"
    description: "Aging Atlas Reveals Cell-Type-Specific Regulation of Pro-longevity Strategies"
    portfolio-type:
      - type: "aging"
      - type: "sc"

  - image: "assets/images/portfolio/6.hearingsc.png"
    url: "https://www.frontiersin.org/articles/10.3389/fncel.2022.962106/full"
    description: "Profiling mouse cochlear cell maturation using 10× Genomics single-cell transcriptomics"
    portfolio-type:
      - type: "sc"
      - type: "hearing"

  - image: "assets/images/portfolio/5.scWGA.png"
    url: "https://genome.cshlp.org/content/32/1/44"
    description: "Low-frequency somatic copy number alterations in normal human lymphocytes revealed by large-scale single-cell whole-genome profiling"
    portfolio-type:
      - type: "aging"
      - type: "sc"

  - image: "assets/images/portfolio/4.small.png"
    url: "https://onlinelibrary.wiley.com/doi/10.1002/smll.201903739"
    description: "Interfacial Nanoinjection‐Based Nanoliter Single‐Cell Analysis"
    portfolio-type:
      - type: "sc"


  - image: "assets/images/portfolio/3.sherry.png"
    url: "https://www.pnas.org/doi/full/10.1073/pnas.1919800117"
    description: "RNA sequencing by direct tagmentation of RNA/DNA hybrids"
    portfolio-type:
      - type: "sc"

  - image: "assets/images/portfolio/2.mica.png"
    url: "https://www.nature.com/articles/s42003-019-0401-y"
    description: "High-throughput single-cell whole-genome amplification through centrifugal emulsification and eMDA"
    portfolio-type:
      - type: "sc"

  - image: "assets/images/portfolio/1.longTn5.png"
    url: "https://pubs.acs.org/doi/10.1021/acsami.8b01560"
    description: "Tagmentation on Microbeads: Restore Long-Range DNA Sequence Information Using Next Generation Sequencing with Library Prepared by Surface-Immobilized Transposomes"
    portfolio-type:
      - type: "sc"

  - image: "assets/images/portfolio/1.digitalcount.png"
    url: "https://pubs.acs.org/doi/10.1021/acsami.7b03146"
    description: "Single-Cell-Based Platform for Copy Number Variation Profiling through Digital Counting of Amplified Genomic DNA Fragments"
    portfolio-type:
      - type: "sc"

  - image: "assets/images/portfolio/1.RNA.png"
    url: "https://pubs.acs.org/doi/10.1021/acs.analchem.6b02581"
    description: "Single Cell Total RNA Sequencing through Isothermal Amplification in Picoliter-Droplet Emulsion"
    portfolio-type:
      - type: "sc"

  - image: "assets/images/portfolio/1.spin.png"
    url: "https://pubs.rsc.org/en/content/articlelanding/2016/LC/C6LC01084A"
    description: "Spinning micropipette liquid emulsion generator for single cell whole genome amplification"
    portfolio-type:
      - type: "sc"

  - image: "assets/images/portfolio/1.chipseq.png"
    url: "https://www.nature.com/articles/cr2014119"
    description: "H3K4me3 epigenomic landscape derived from ChIP-Seq of 1,000 mouse early embryonic cells"
    portfolio-type:
      - type: "sc"
 
  - image: "assets/images/portfolio/1.eWGA.png"
    url: "https://www.pnas.org/doi/full/10.1073/pnas.1513988112"
    description: "Uniform and accurate single-cell sequencing based on emulsion whole-genome amplification"
    portfolio-type:
      - type: "sc"

  - image: "assets/images/portfolio/1.scRNA.png"
    url: "https://www.pnas.org/doi/full/10.1073/pnas.1402030111"
    description: "Microfluidic single-cell whole-transcriptome sequencing"
    portfolio-type:
      - type: "sc"

  - image: "assets/images/portfolio/1.dPCR.png"
    url: "https://pubs.acs.org/doi/10.1021/ac300761n"
    description: "Digital Polymerase Chain Reaction in an Array of Femtoliter Polydimethylsiloxane Microreactors"
    portfolio-type:
      - type: "sc"
  
  - image: "assets/images/portfolio/1.opt.png"
    url: "https://opg.optica.org/oe/fulltext.cfm?uri=oe-20-8-8824&id=231681"
    description: "High dynamic range optical projection tomography (HDR-OPT)"
    portfolio-type:
      - type: "sc"

